apiVersion: apps/v1
kind: Deployment
metadata:
  name: installment-service
  labels:
    app: installment-service
spec:
  selector:
    matchLabels:
      app: installment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: installment-service
    spec:
      containers:
        - name: installment-service
          image: iriquelme/installment-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST
            - name: POSTGRES_DB_INSTALLMENT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_INSTALLMENT_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: installment-service
  labels:
    app: installment-service
spec:
  selector:
    app: installment-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer