apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST: postgres
  
  DB_STUDENT_NAME: student_db

  DB_INSTALLMENT_NAME: installment_db
  
  DB_ADMINISTRATION_NAME: administration_db