apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres

  POSTGRES_DB_ADMINISTRATION: administration_db

  POSTGRES_DB_INSTALLMENT: installment_db

  POSTGRES_DB_STUDENT: student_db